### ISSUE TITLE
cp -R steps list non existent dirs.

### ISSUE THREAD

**Issue by Jmainguy** [LucidWorks/fusion-upgrade-scripts#2]
Steps 9 and 10

cp -r fusion/data/connectors/crawldb/\* fusion-new/data/connectors/crawldb/
cp -R fusion/data/connectors/lucid.jdbc/\* fusion-new/data/connectors/lucid.jdbc/

in Fusion 1.2.3 there is no fusion-new/data/connectors/crawldb/ and there is no fusion-new/data/connectors/lucid.jdbc/

The closest I could find was fusion/connectors/plugins/lucid.jdbc

So, I am not going to do either step, Wish me luck

**Comment by kiranchitturi** [comment]
yeah, skipping those steps should be fine
